name: Update version.js

on:
  push:
    branches:
      - main  # Falls du eine andere Branch benutzt, ändere das hier

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git version
        run: echo "const version = '$(git rev-parse --short HEAD)';" > version.js

      - name: Commit and push version update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add version.js
          git commit -m "Update version.js" || echo "No changes to commit"
          git push
