name: Update version.js

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Erlaubt das Schreiben ins Repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git version
        run: echo "const version = '$(git rev-parse --short HEAD)';" > version.js

      - name: Commit and push version update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add version.js
          git commit -m "Update version.js" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
